LINK_EXPIRE_HOURS = 4

# Limits
NEWEST_PRODUCT_IN_PAGE_LIMIT = 10
HOT_PRODUCT_IN_PAGE_LIMIT = 10
BEST_PRODUCT_IN_PAGE_LIMIT = 10
MOST_POPULAR_TAGS_LIMIT = 5

# Error messages
PRODUCT_NOT_FOUND_MSG = 'Product not found.'
