# Generated by Django 4.0.5 on 2022-06-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_user_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('product_id', 'cart_id'), name='unique_cartitem_constraint'),
        ),
    ]
