# Generated by Django 4.0.5 on 2022-06-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productattributevalue',
            constraint=models.UniqueConstraint(fields=('product_id', 'attribute_id'), name='unique_value_constraint'),
        ),
    ]
