# Generated by Django 4.0.5 on 2022-09-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_alter_producttype_options_alter_category_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, help_text='How many products have left.', verbose_name='Quantity'),
        ),
    ]
