# Generated by Django 4.0.5 on 2022-09-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_limited',
            field=models.BooleanField(default=True, help_text='Depends on quantity.', verbose_name='Limited'),
        ),
    ]
