# Generated by Django 4.0.5 on 2022-09-17 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_city_company_customuser_company'),
        ('catalogue', '0010_product_is_limited'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='accounts.company', verbose_name='Company'),
        ),
    ]
