# Generated by Django 4.0.5 on 2022-09-17 04:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_product_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, help_text='How many products have left.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity'),
        ),
    ]
