# Generated by Django 4.0.5 on 2022-09-17 06:35

import catalogue.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(default='Alt text', help_text='This displays when image fails to load.', max_length=255, verbose_name='Alternative text'),
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('file', models.FileField(help_text='User will be able to download this file after purchase.', upload_to=catalogue.utils.get_product_file_path, verbose_name='File')),
                ('link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Download link')),
                ('is_main', models.BooleanField(default=False, verbose_name='Main file')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='catalogue.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product File',
                'verbose_name_plural': 'Product Files',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ActivationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Must be unique', max_length=512, unique=True, verbose_name='Activation key')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiry date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activation_keys', to='catalogue.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-expired_at'],
            },
        ),
    ]
