# Generated by Django 4.0.5 on 2022-09-17 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_alter_productimage_alt_text_productfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='catalogue.product', verbose_name='Product'),
        ),
    ]
