# Generated by Django 4.0.5 on 2022-09-18 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_status'),
        ('catalogue', '0015_alter_activationkey_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationkey',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activation_keys', to='orders.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='product',
            name='keys_limit',
            field=models.IntegerField(default=1, help_text='How many keys should user get per purchase.', verbose_name='Keys limit'),
        ),
    ]
