# Generated by Django 4.0.5 on 2022-09-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_activationkey_order_product_keys_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='guide',
            field=models.TextField(default='Install files and activate keys.', help_text='Installation/Activation Guide', verbose_name='Guide'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='keys_limit',
            field=models.IntegerField(default=1, help_text='How many keys should user get per purchase. If 0, then no keys required.', verbose_name='Keys limit'),
        ),
    ]
