# Generated by Django 4.0.5 on 2022-10-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_onetimeurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimeurl',
            name='expired_at',
            field=models.DateTimeField(default='2022-10-01T03:26:07Z', editable=False, verbose_name='Expiry date'),
            preserve_default=False,
        ),
    ]
