# Generated by Django 4.0.5 on 2022-06-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('DONE', 'Done'), ('REFUNDED', 'Refunded')], default='IN_PROGRESS', max_length=20, verbose_name='Status'),
        ),
    ]
