# Generated by Django 4.0.5 on 2022-08-07 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order item', 'verbose_name_plural': 'Order items'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='unique_orderitem_constraint',
        ),
        migrations.AlterField(
            model_name='address',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='orders.payment', verbose_name='Payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Declined', 'Declined'), ('Accepted', 'Accepted'), ('Done', 'Done'), ('In progress', 'In Progress'), ('Refunded', 'Refunded')], default='In progress', max_length=255, verbose_name='Order status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], default='Cash', max_length=10, verbose_name='Payment Type'),
        ),
    ]
