# Generated by Django 4.0.5 on 2022-08-07 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_delete_transaction_alter_address_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_type',
            new_name='type',
        ),
    ]
