# Generated by Django 4.0.5 on 2022-08-07 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_payment_type_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.RESTRICT, to='orders.order', verbose_name='Order'),
            preserve_default=False,
        ),
    ]
