# Generated by Django 4.0.5 on 2022-08-28 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum 9999999999.99', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Regular price'),
        ),
    ]
