# Generated by Django 4.0.5 on 2022-09-08 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum 9999999999.99', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Total price'),
        ),
    ]
