# Generated by Django 4.0.5 on 2022-09-17 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
