# Generated by Django 4.0.5 on 2022-09-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_delete_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In progress', 'In Progress'), ('Complete', 'Complete'), ('Canceled', 'Canceled'), ('Refunded', 'Refunded'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='In progress', max_length=255, verbose_name='Order status'),
        ),
    ]
