# Generated by Django 4.0.5 on 2022-09-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETE', 'Complete'), ('CANCELED', 'Canceled'), ('REFUNDED', 'Refunded')], default='IN_PROGRESS', max_length=255, verbose_name='Order status'),
        ),
    ]
