# Generated by Django 4.0.5 on 2022-09-08 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0012_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], default='Cash', max_length=10, verbose_name='Payment Type')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Maximum 99999.99', max_digits=7, verbose_name='Total price')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
