# Generated by Django 4.0.5 on 2022-09-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False, verbose_name='Success')),
                ('message', models.CharField(default='', max_length=512, verbose_name='Message')),
                ('transaction_id', models.CharField(max_length=512, unique=True, verbose_name='Transaction ID')),
                ('model', models.JSONField(blank=True, null=True, verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
