name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    # Define postgres service (like in docker-compose.yml)
    services:
      postgres-db:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432
    # If you want to test multiple python versions
    strategy:
      matrix:
        python-version: ["3.9"]   # ["3.8", "3.9", "3.10"]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Requirements
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: |
          cat .env.sample >> .env
          cd reclothes
          python manage.py test
